问题1： Description: Cannot determine embedded database driver class for database type NONE Action: If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).
解决1：加数据库配置

问题2：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name
 'org.springframework.boot.autoconfigure.session.SessionAutoConfiguration$SessionRepositoryValidator':
 Invocation of init method failed; nested exception is java.lang.IllegalArgumentException:

 No Spring Session store is configured: set the 'spring.session.store-type' property

解决2：加redis配置